build:
  nodes:
    coverage:
      tests:
        override:
          - command: XDEBUG_MODE=coverage composer test
            coverage:
              file: build/coverage/log/coverage.xml
              format: clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run

checks:


filter:
    excluded_paths:
        - 'test/*'
        - 'vendor/*'

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
